# Ultralytics YOLO 🚀, GPL-3.0 license

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolo11n.yaml' will call yolo11.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024] 
  m: [0.50, 1.00, 512]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.50, 512]

# SimMIM Encoder
embed_dim: 128
depths: [ 2, 2, 18, 2 ] # [64*80*80,128*40*40,256*20*20,256*20*20]
num_heads: [ 4, 8, 16, 32 ]
window_size: 4
patch_size: 4
img_size: 640
mask_radio: 0.6
mask_patch_size: 32

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [null, 2, 'nearest']] # 4 
  - [[-1, 1], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C3k2, [512, False]]  # 6

  - [-1, 1, nn.Upsample, [null, 2, 'nearest']]
  - [[-1, 0], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C3k2, [256, False]]  # 9 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 6], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C3k2, [512, False]]  # 12 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 2], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C3k2, [1024, True]]  # 15 (P5/32-large)

  - [[9, 12, 15], 1, Detect, [nc]]  # Detect(P3, P4, P5)
